export const initialStyles = {
    'full-container': {
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'space-between',
        height: 'calc(100vh - 10rem)',
        maxHeight: 'calc(100vh - 10rem)',
        margin: '5rem',
    },
    'chat-container': {
        display: 'flex',
        flexDirection: 'column',
        padding: '.75rem',
        gap: '2rem',
        overflow: 'auto',
        width: '100%',
        marginBottom: '5rem',
    },
    'user-bubble': {
        padding: '1rem',
        border: '1px solid #ccc',
        borderRadius: '10px',
        backgroundColor: '#f0f0f0',
        fontSize: '1.2rem',
        width: 'fit-content',
        height: 'fit-content',
        maxWidth: '40%',
        textAlign: 'left',
        marginLeft: 'auto',
        fontFamily: '"Roboto", sans-serif',
    },
    'ai-bubble': {
        padding: '1rem',
        border: '1px solid #ccc',
        backgroundColor: '#ffffff',
        borderRadius: '10px',
        fontSize: '1.2rem',
        width: 'fit-content',
        height: 'fit-content',
        maxWidth: '80%',
        textAlign: 'left',
        marginRight: 'auto',
        fontFamily: '"Roboto", sans-serif',
    },
    'input-container': {
        backgroundColor: '#ffffff',
        border: '2px solid #ccc',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        marginTop: 'auto',
        borderRadius: '10px',
        padding: '.75rem',
        margin: '0 5rem',
        width: 'calc(100% - 1.5rem)',
        gap: '1rem',
    },
    'input-field': {
        fontSize: '1.2rem',
        fontFamily: '"Roboto", sans-serif',
        border: 'none',
        overflowWrap: 'break-word',
        width: '100%',
        lineHeight: '1.5rem',
        maxHeight: 'calc(1.5rem * 6)',
        overflowY: 'auto',
        resize: 'none',
    },
    'input-icon': {
        padding: '.7rem',
        marginLeft: 'auto',
        marginRight: '1rem',
        borderRadius: '50%',
        transition: 'background-color 0.3s',
    },
    'loading': {
        position: 'absolute',
        top: '0',
        bottom: '0',
        left: '0',
        right: '0',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        background: 'rgba(255,255,255,0.7)',
    },
    'spinner': {
        fontSize: '2rem',
    },
};